[options]
addons_path={{ADDONS_PATH}}
data_dir={{DATA_DIR}}
logfile={{ODOO_LOG_FILE}}

db_host=localhost
db_port=5432
db_user={{POSTGRES_USER}}
db_password={{DB_PASSWORD}}

list_db=False
admin_passwd={{ADMIN_PASSWORD}}
dbfilter=^{{POSTGRES_DB}}$
http_port={{ODOO_PORT}}
